sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install .

script:
  - nosetests -P tests
