sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: '3.7'
      sudo: true
      dist: xenial

install:
  - pip install .

script:
  - pytest
